### ISSUE TITLE
[Manuale Sviluppatore] - Risultati Verifica

### ISSUE THREAD

**Issue by oeconti** [LeafSWE/Documents-RQ#26]
- [x] Sez. 1.2 -> Punti elenco 5,6,7 terminano con il punto anziché con il punto e virgola
- [x] Sez. 2 -> I sistemi operativi sono uno in grassetto ed un in corsivo, perché?
- [x] Sez. 2-4 -> Raccomended in Reccomended
- [x] Sez. 5 -> Toglierei "una" Navigazione Indoor lasciando solo Navigazione Indoor
- [x] Sez. 5.1 -> Titolo sezione -> è voluta la "&"? Non la metterei
- [x] Sez. 5.1 -> "Una ROI e quindi un Beacon rappresenta più POI" -> Manca la virgola
- [x] Sez. 5.1 -> "Poiché un POI può essere che abbia più punti d’accesso, si pensi ad una stanza con più di una porta d’accesso, è previsto che un singolo POI possa appartenere a più ROI." -> Periodo da rivedere -> "Poiché è possibile che un POI abbia più punti di accesso (si pensi ad una stanza ...) ..."
- [x] Sez. 5.1 -> "Nella figura 10 si vede come il POI al centro appartiene sia alla ROI 1 sia alla ROI 2 ." -> "Appartenga" ?
- [x] Sez. 5.3 -> "gli spazi interni dell’edificio in un grafo possiamo sfruttare tutta la conoscenza matematica su questi." -> Manca la virgola dopo "grafo"
- [x] Sez. 5.4 -> "Se consideriamo ogni piano di un edificio un grafo" -> "Se consideriamo ogni piano di un edificio come un grafo, .."
- [x] Sez. 5.5 -> "I dati trasmessi dal Beacon sono Major e Minor, si tratta di due stringhe di cinque caratteri numerici." -> "I dati trasmessi dal Beacon sono Major e Minor ovvero due stringhe composte da cinque caratteri numerici."
- [x] Sez. 5.5 -> "dal team Leaf per" -> Manca spazio?
- [x] Sez. 5.5 -> "Ciò perché l’applicazione" -> Sostituire con: "L'aplicazione infatti.."
- [x] Sez. 5.6 -> "una ROI non contenga troppi POI;" -> Quanti sono troppi POI?
- [x] Sez. 5.6 -> "per ogni Edge identificato rilevare le informazioni necessarie per descriverlo in toto." -> Mancano i due punti alla fine
- [x] Sez. 5.6 -> Punto 7 -> sostituire "premi" con "prime"
- [x] Sez. 6.1.1 -> "È compito del Presenter raccogliere questi segnali ed elaborarli in qualche modo." -> Togliere "qualche modo"
- [x] Sez. 6.1.2 -> Specificare "comunità Android"
- [x] Sez. 6.2 -> "e garantire" -> garantisce
- [x] Sez. 6.3.2 -> "un metodo può essere annotato" -> Deve essere maiuscolo "Un"
- [x] Sez. 6.3.4 -> "implementazioni da" -> "dà"
- [x] Sez. 6.3.4 -> "sono tutte o Activity oppure Application" -> togliere "o"
- [x] Sez. 7.0 -> "alla documentazione ufficiale comprese le componenti interne." -> Manca la virgola dopo ufficiale
- [x] Sez. 7.1.2 -> "vuota, ossia priva di informazioni dell’edificio. Ciò significa che il device non ha ancora rilevato un Beacon riconosciuto dall’applicazione." -> La HomeView non è vuota anche se l'utente non ha scaricato la mappa?
- [x] Sez, 7.1.4 -> Il Ranging è l’operazione svolta in background per riconoscere i Beacon circostanti senza eccessiva precisione mentre il Monitoring è l’operazione che segue in cui i beacon vengono invece rilevati con tutte le informazioni e con più precisamente. -> Manca la virgola dopo "segue" e alla fine deve essere con più "precisione"
- [x] Sez. 7.1.5 -> Manca lo spazio dopo "PhotoService"
- [x] Sez. 7.1.5 -> "Tali componenti sono prelevate e costruite facendo uso di semplici oggetti data" -> Cos'è data?
- [x] Sez. 7.3.3 -> "attraverso l’interfaccia NavigationViewPoiCategoryActivity comunica con" -> Manca spazio o è presente un carattere strano trea View e Poi
- [x] Sez. 7.3.4 -> "Perché NavigatorImp funzioni come si deve" -> "Affinchè NavigatorImp funzioni, " (non scrivere come si deve)
- [x] Sez. 7.3.4 -> si è ( startROI )alla destinazione -> Manca spazio dopo la parentesi
- [x] Sez. 7.3.5 -> "Compass rende disponibili i metodi per registrare i listener ai sensori e per rimuoverla." -> rimuoverla?
- [x] Sez. 7.3.6 -> "com.leaf.clips.model.navigatorvengono" -> Manca spazio
- [x] Sez. 7.4.3 -> Interfacce e classi: 2 classi non hanno link
- [x] Sez. 8.5.2 -> Spostare nella pagina successiva la sezione se possibile
- [x] Sez. 8.5.8 -> "url Rappresenta l’URL a cui è possibile recuperare l’immagine." -> "da cui"
- [x] Sez. A.2 -> unBind Service: è un Service che comunica con le altre componenti dell’applicazione solo attraverso messaggi Intente BroadcastReceiver; -> Manca spazio su "Intente"
- [x] Sez. Glossario: -> AltBeacon, Framework, Wrapper -> I puntini alla fine?

**Comment by EduBic** [comment]
**Sez. 7.1.2** io penso che l'applicazione in quel caso scarichi la mappa

 **Sez. 8.5.2**  la scelta è stata fatta per ingrandire il diagramma ER.

**Comment by davidecastello** [comment]
Verificato
