### ISSUE TITLE
[SP] Verifica Sperimentazioni Pratiche

### ISSUE THREAD

**Issue by tfederico** [LeafSWE/Documents-RQ#29]
- [x] sicuri che sui beacon all'ingresso la potenza sia 0?
- [x] aggiungere a glossario
  - [x] algoritmo di Dijkstra
  - [x] card
  - [x] impianto
- [x] 3.2 non inizierei un paragrafo dicendo "l'algoritmo ha un problema" 
- [ ] nella pagina 13 c'è una sola riga di testo
- [x] pagina 15 seconda riga, manca una parentesi
- [x] pagina 15 "orientarsi meglio riguardo ai servizi offerti dall’edificio" forse riguardo alle destinazioni offerte dall'edificio?
- [ ] 4.2 "Le istruzioni vengono fornite sotto forma di lista ordinata: devono essere seguite **pedissequamente** per raggiungere la destinazione." cambierei la frase, in particolare il **pedissequamente**
- [x] 4.2 "L’istruzione corrente viene evidenziata, per essere maggiormente visibile" spiegare come viene evidenziata
- [ ] 5 e 5.1 sono concetti da Norme di Progetto, idem 6.3.1
- [ ] 6.3.1 "Se non è possibile reperire i risultati perché l’applicazione non li supporta, le variabili output sono marcate con N.S.;"  se N.S. viene indicato in rosso viene inteso come link poiché il colore in altri documenti è stato usato per quello scopo
- [x] spiegare a cosa corrispondono le sigle N.R. e N.S. anche se può essere dedotto dal contesto
- [x] 6.4.3 "Questo escamotage" userei "questa specifica" anziché escamotage, altrimenti sembra una fregatura
- [x] 6.5 "Entro lo svolgimento [...]" formulare meglio l'ultimo paragrafo, frasi troppo contorte
- [x] 7 incoerenza tra le date indicate nel titolo e alcune label di tabelle
- [x]  7.4.1 ha senso ripetere come viene definita una prova più volte?
- [ ] aggiungerei alle problematiche UX quelle rilevate sul Nexus 5 (la lista che non si espande) e direi che l'abbiamo anche segnalato al proponente

**Comment by black2279** [comment]
- [x] pag.29 non "Beacon Power Adapter"  ma "Beacon Power Area"

**Comment by o5k1** [comment]
- Sui beacon all'ingresso, la potenza è 2

**Comment by EduBic** [comment]
Ingresso intendi entrate torri?

Quando è stato provato tutto era a 0, io nella scatola ho tutti i beacon a 0. Spero che sia stato provato qualche volta la potenza 2.

**Comment by black2279** [comment]
- [x] Prova 1D.1 è presente aula "1A100" ?
- [x] Prova 2A.1 è sbagliata la categoria o la destinazione
- [x] Prova 2B.1 è sbagliata la categoria o la destinazione
- [x] Prova 3 punto 5 della procedura non completo o incorretto
- [x] Prova 12.A $RESULT2 sbagliato

**Comment by EduBic** [comment]
>  7.4.1 ha senso ripetere come viene definita una prova più volte?

Ha senso perché per ogni prova si potrebbe specificare una concretizzazione diversa. Quel modo di classificarle non vincola tutte le sperimentazioni.

> nella pagina 13 c'è una sola riga di testo

Non posso farci nulla, dispiace

> 4.2 "Le istruzioni vengono fornite sotto forma di lista ordinata: devono essere seguite pedissequamente per raggiungere la destinazione." cambierei la frase, in particolare il pedissequamente

Se non segui alla lettere le istruzioni non ti viene garantito il raggiungimento della destinazione per cui a me sembra adatta la frase.

> 5 e 5.1 sono concetti da Norme di Progetto, idem 6.3.1

In un contesto dove le prove vengono svolte da terzi (miriade) le norme di progetto cambiano, legarle al documento era l'unico modo per rendere più indipendente il documento

> 6.3.1 "Se non è possibile reperire i risultati perché l’applicazione non li supporta, le variabili output sono marcate con N.S.;" se N.S. viene indicato in rosso viene inteso come link poiché il colore in altri documenti è stato usato per quello scopo

Per quanto mi riguarda il documento è slegato da tale norma, anzi nessuna norma definisce l'uso dei colori nei documenti per cui ognuno può definire la propria anche se differente. L'importante che sia descritto all'interno del documento.

> spiegare a cosa corrispondono le sigle N.R. e N.S. anche se può essere dedotto dal contesto

Sono spiegati per bene

> aggiungerei alle problematiche UX quelle rilevate sul Nexus 5 (la lista che non si espande) e direi che l'abbiamo anche segnalato al proponente

Non è oggetto della prova...

**Comment by tfederico** [comment]
@EduBic 
"Se non è possibile reperire i risultati perché l’applicazione non li supporta, le variabili output sono marcate con N.S" quello che intendo io è mettere "N.S. (Non Supportata)" e non è esplicitato da nessuna parte in questo modo

**Comment by tfederico** [comment]
@EduBic
"Ogni prova concettuale è effettuata attraverso una sua concretizzazione. Una concretizzazione rappresenta una prova reale effettuata sul campo, essa è identificata da un codice univoco:
Prova [N][I].[T]"
Secondo questa frase tutte le prove vengono definite allo stesso modo, quindi non ha senso ripeterlo per ogni prova.

**Comment by tfederico** [comment]
@EduBic 
"L’algoritmo descritto precedentemente soffre di un problema: non riesce a fare assunzioni sulla direzione dell’utente."
Il compito dell'algoritmo non è calcolare direzioni ma percorsi, quindi l'algoritmo non soffre di un problema ma quanto più di una mancanza, poiché non fa una cosa in un modo sbagliato ma non la fa proprio perché non è un suo compito.

**Comment by black2279** [comment]
- [x] Prova 6 include anche TS13
- [x] Prova 9 include anche TS3.1 , TS3.3
- [x] Prova 15 include anche TS1.2 , TS1.3
