### ISSUE TITLE
Argomenti presentazione

### ISSUE THREAD

**Issue by o5k1** [LeafSWE/Documents-RQ#30]
Vi chiedo di prendervi carico degli argomenti mancanti per la presentazione. Quando ne avete scelto uno o più, spuntate la casella e commentate indicando l'argomento scelto. Grazie.
- [x] Come il meccanismo delle preferenze permette all'app di adattarsi alle esigenze di 
  diverse tipologie di utenti;
- [x] Come la bussola è stata utilizzata per una migliore esperienza di navigazione;
- [x] La possibilità di scaricare nuove mappe, che rende CLIPS scalabile;
- [x] Ruolo dei beacon e best-practice per la mappatura di un edificio (al fine di espandere gli edifici
  supportati da CLIPS) --> comprendere la sezione DEV, manuale sviluppatore, javadoc e la loro utilità nell'espandere/manutenere il sistema;
- [x] Possibili evoluzioni dell'applicazione. Ad esempio verso l'accessibilità, parlando del TTS/Sonar e di come un prodotto del genere potrebbe migliorare la vita di persone con disabilità visive (ipovedenti);
- [ ] Le prove di laboratorio;
- [x] Discorso qualità: quali accorgimenti (test compresi) sono stati presi per garantire un prodotto di qualità verificabile;
- [ ] Ore rendicontate, prezzo proposto e confronto con preventivo.

**Comment by davidecastello** [comment]
Scaricare nuove mappe + ruolo dei beacon e mappatura dell'edificio

**Comment by oeconti** [comment]
Possibili evoluzioni + preferenze

**Comment by o5k1** [comment]
@tfederico possibili evoluzioni

**Comment by oeconti** [comment]
La bussola allora
Il 12/Giu/2016 23:33, "Octa Git" octagitux@gmail.com ha scritto:

> Possibili evoluzioni + preferenze

**Comment by EduBic** [comment]
Ore rendicontate etc.

**Comment by o5k1** [comment]
@EduBic non conviene che tu parli del laboratorio?

**Comment by EduBic** [comment]
Posso anche. Li ho entrambi svolti

**Comment by black2279** [comment]
> Discorso qualità: quali accorgimenti (test compresi) sono stati presi per garantire un prodotto di qualità verificabile;  

ok

**Comment by o5k1** [comment]
Data la natura atipica del nostro collaudo (che si svolgerà necessariamente fuori dall'aula nella quale si terrà l'elevator pitch), ho redistribuito alcuni temi. Inoltre, la parte "Durante collaudo" sarà da svolgersi come una conversazione con Miriade/Tullio in quanto saremo tutti in corridoio per il collaudo. 

La parte di Marco e Davide è interessante per Miriade quindi può essere loro esposta durante il collaudo.
Per quanto riguarda Cristian ed Eduard, vi chiedo di preparare la vostra parte (con slide) ed essere pronti sia ad esporla che a proporla come conversazione (in quanto non è interessante per Miriade ma per Tullio, che però sarà probabilmente in aula a proseguire le RA mentre noi facciamo il collaudo).

Meglio di così non saprei come fare, per qualsiasi proposta sono a vostra disposizione.

Elevator pitch:
- [Andrea] Introduzione + video + screencast navigazione (2 min.);
- [Oscar] Preferenze, bussola + scaricare nuove mappe;
- [Federico] Evoluzioni.

Durante collaudo:
- [Davide] Ruolo dei beacon e mappatura edificio (finchè il resto del gruppo posiziona i beacon);
- [Marco] Prove di laboratorio (finchè il resto del gruppo posiziona i beacon);
- [Cristian] Discorso qualità (dopo collaudo);
- [Eduard] Ore rendicontate, prezzo proposto, confronto con preventivo (dopo collaudo).

**Comment by o5k1** [comment]
Se @davidecastello non se la sente di usare Vysor, si può cambiare con @black2279 o con chiunque se la senta.
Struttura presentazione modificata come discusso:
- [Andrea] Introduzione, video;
- [Oscar] Preferenze, bussola + scaricare nuove mappe;
- [Federico] Evoluzioni;
- [Davide] Screencast nell'ottica di istruire Miriade/Tullio su come usare l'app per effettuare il collaudo (In pratica si mostra come effettuare navigazione ed accedere ai Floating Button della home);
- [Marco] Introduzione alle prove di laboratorio (prima di spostarsi in corridoio);
- [Cristian] Ruolo dei beacon e mappatura edificio (finchè il resto del gruppo posiziona i beacon);
- [Eduard] Ore rendicontate, prezzo proposto, confronto con preventivo (dopo collaudo).

**Comment by black2279** [comment]
> [Cristian] Ruolo dei beacon e mappatura edificio (finchè il resto del gruppo posiziona i beacon);

Quindi serve solo il discorso?
